### ISSUE TITLE
When Importing a apk and starting the game it says minecraft has exited with a non zero code

### ISSUE THREAD

**Issue by OofimusPlayz** [ChristopherHX/mcpelauncher-ui-manifest#11]

**Comment by ChristopherHX** [comment]
Not an issue, importing invalid or pirated apks is unsupported. (
Please buy the game (google play store) and sign in to google.

Maybe the error popup just disappeared see
https://github.com/minecraft-linux/mcpelauncher-ui-manifest/issues/22
