### ISSUE TITLE
Error while extracting the file: Failed to stat the specified file

### ISSUE THREAD

**Issue by Saraistupid** [ChristopherHX/mcpelauncher-ui-manifest#13]
I'm using an APK, using `mcpelauncher-extract` works but not from the launcher it self, is there any fix for that?
INFO:
Version 1.16.0.51
Distro: Solus

**Comment by ChristopherHX** [comment]
- Buy the game on the google play store.
   - Setup an Android vm if you don't own a real device.
      You need to login to google play on android once, to be able to buy games.
- Sign in to google in this launcher
- press "download and play" to get the game
  - You can choose to download / play any versions between alpha 0.12 and "The nether update" 1.16.10.02

**Pirating apk's is bad and illegal in my country**

Why you get this error:
Opening your apk worked.
This zip file doesn't contain a readable "AndroidManifest.xml"
https://github.com/minecraft-linux/mcpelauncher-ui-qt/blob/474ed58a54fd4eb98231a8942a5fb1f1a635fb01/apkextractiontask.cpp#L37
This calles
https://github.com/minecraft-linux/mcpelauncher-extract/blob/586011d9d78cc9a9fdfb03fa9453a3d9ae0dddde/lib/zip_extractor.cpp#L96
But it failed to find it.
The mcpelauncher-extract don't read the file
  - To get the versionscode / name

**Comment by Saraistupid** [comment]
Ah ok, thanks
