### ISSUE TITLE
1.16.20.03 not working

### ISSUE THREAD

**Issue by YouthHalo** [ChristopherHX/mcpelauncher-ui-manifest#14]
I try to play 1.16.20.03 on Debian but it doesn't work, tried reinstalling it and logging out and in, but no good

**Comment by Ubuntuify** [comment]
> # This won't work with the current 1.16.20 Version

The _latest release_ of the **AppImage** clearly _states_ that it does not support **1.16.20** version yet. Please wait for the developer to add support.
