### ISSUE TITLE
Issules with connection to Google Play servers (Appimage and Flatpack)

### ISSUE THREAD

**Issue by amuerta** [ChristopherHX/mcpelauncher-ui-manifest#16]
On both Appimage and Flatpak i'm not able to download the game or login

On latest Appimage release i'm not able to login because Google's loading screen after **Sign In windows**

On Flatpak version of launcher Download button saying Please wait, 
Troubleshooter prints an error: 
```
Failed to obtain the gameversion
Please check your internet connection and / or login to Google Play again Statuscode of playVerChannle 1
```

**Comment by ChristopherHX** [comment]
Your system files are too new for this old software.

See here for a workaroud ( AppImage ) https://github.com/minecraft-linux/mcpelauncher-manifest/issues/656#issuecomment-1032808033

**The flatpak is marked as End of Live, app still working on ubuntu 20.04**

**Comment by amuerta** [comment]
### Thank you! 
Working like a charm right after running in under flags :)
_I think it would be a good idea to add something like compatibility button in logining menu for noobs like me_
if someone else have this issule under arch/fedora/any other rolling release distribution and you didn't understand what to do
 **just run** 
```
QTWEBENGINE_CHROMIUM_FLAGS="--enable-logging --log-level=0 --v=3 --single-process --no-sandbox" /path/to/your/appimage-minecraft-launcher
```
Issue was solved :)
