### ISSUE TITLE
Error after sign in

### ISSUE THREAD

**Issue by gerardreches** [ChristopherHX/mcpelauncher-ui-manifest#3]
MacOS Catalina 10.15.X after the second login.

> The associated promise has been destructed prior to the associated state becoming ready. Please login again.

**Comment by ChristopherHX** [comment]
Should be fixed with https://github.com/ChristopherHX/mcpelauncher-ui-manifest/commit/8b7543e59133615749e813fcd9873d5cb7f37954

**Comment by ChristopherHX** [comment]
A Experimental Catalina compatible version is now available (using 64bit Minecraft)
