### ISSUE TITLE
Sometimes mcpelauncher-ui-qt never closes

### ISSUE THREAD

**Issue by 0xCatPKG** [ChristopherHX/mcpelauncher-ui-manifest#4]
Sometimes mcpelauncher-ui-qt never closes after closing of window and when you starting launcher again you will get 2 mcpelauncher-ui-qt processes, one showing window, and one running in background

**Comment by ChristopherHX** [comment]
[Fixed in ng (branch, my stable now use the same improved ui)](https://github.com/minecraft-linux/mcpelauncher-ui-manifest/tree/ng).
It's close handler was very broken.
