### ISSUE TITLE
Can't launch from steamos-session

### ISSUE THREAD

**Issue by 4ifi** [ChristopherHX/mcpelauncher-ui-manifest#7]
Can't correctly launch from steamos-session. It starts in invalid resolution, mouse lags and can't click play button.

**Comment by ChristopherHX** [comment]
Can't reproduce, because I only use steam on windows.

**Comment by 4ifi** [comment]
@ChristopherHX , thanks for your answer. Another question if steamos DE isn't supported. Can I run launcher and minecraft in fullscreen resolution via xinit or startx without WM and DE from tty shell? It only starts in small window which can't be resized with f11 key and config file.

**Comment by ChristopherHX** [comment]
use the `-ww width` and `-wh height` switches.
`mcpelauncher-client --help` for more info.
or the profile editor in the launcher window (if it is usable :/), if you launch it with it

Appimage type `M.AppImage --appimage-mount`, it prints a path of the content, you find then the binaries inside `usr/bin/`

**Comment by 4ifi** [comment]
It now starts in full screen resolution from tty & steamos DE!
I wrote simple script and I share it with people:
```bash
#!/bin/bash
version=1.16.0.51
/home/user/Minecraft_Bedrock_Launcher-*-x86_64.AppImage --appimage-mount > /tmp/mine.txt &
sleep 1
dir=$(cat /tmp/mine.txt)
rm /tmp/mine.txt
$dir/usr/bin/mcpelauncher-client -ww 1920 -wh 1080 -dg /home/user/.local/share/mcpelauncher/versions/$version -dd /home/user/.local/share/mcpelauncher
kill %1
```

But I have invisible mouse cursor when I launch from tty & ugly steam cursor when launch from steamos-session. How to fix it?

**Comment by ChristopherHX** [comment]
@4ifi If you launch the gui from steamos, is the ui oversized?
like https://github.com/ChristopherHX/mcpelauncher-ui-manifest/issues/9#issue-638335163

**Comment by 4ifi** [comment]
@ChristopherHX I won't use launcher ui anymore because I can easily mount appimage and easily launch with mcpelauncher-client. I wrote you 1 month ago that launcher launches in wrong resolution and I can't do anything (can't use mouse and can't print). My cursor is invisible when I launch from tty and my cursor is big and ugly (design made by Valve) when I launch from steamos-session. I need Adwaita cursor when I launch Minecraft from tty and steamos-session.

**Comment by 4ifi** [comment]
@ChristopherHX I found temp fix. Just replaced ingame steamos ugly cursor /usr/share/icons/steam/arrow.png with [small adwaita cursor](https://user-images.githubusercontent.com/12215530/84658565-6c2c1580-af59-11ea-9720-f03c93ecd0ab.png). I also made [medium](https://user-images.githubusercontent.com/12215530/84658797-c331ea80-af59-11ea-996e-8d82855a3f26.png) and [big](https://user-images.githubusercontent.com/12215530/84658824-cf1dac80-af59-11ea-8d34-9896a57c9565.png) adwaita cursor versions for people who need. Just download cursor you need. Still can't fix invisible cursor when launch from tty.

**Comment by 4ifi** [comment]
@ChristopherHX Found same issue with cursor in SuperTuxKart and other games using system and non-game cursor. Lol... So I think it's impossible to fix this bug. Don't waste your time because nobody fixes this bug.
